# Generated by Django 5.0.7 on 2024-07-30 13:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectoffer',
            name='catOne',
            field=models.CharField(choices=[('IT', 'IT'), ('Finance', 'FINANCE'), ('Healthcare', 'HEALTHCARE'), ('Education', 'EDUCATION'), ('Marketing', 'MARKETING'), ('Design', 'DESIGN'), ('Engineering', 'ENGINEERING'), ('Customer Service', 'CUSTOMER_SERVICE'), ('Legal', 'LEGAL'), ('Sales', 'SALES'), ('Human Resources', 'HR'), ('Writing and Editing', 'WRITING_EDITING'), ('Data Science and Analytics', 'DATA_SCIENCE'), ('Project Management', 'PROJECT_MANAGEMENT'), ('Consulting', 'CONSULTING'), ('Operations', 'OPERATIONS'), ('Research and Development', 'RESEARCH_DEVELOPMENT'), ('Administrative Support', 'ADMIN_SUPPORT'), ('Construction', 'CONSTRUCTION'), ('Real Estate', 'REAL_ESTATE'), ('Entertainment and Media', 'ENTERTAINMENT_MEDIA'), ('Other', 'OTHER')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='projectoffer',
            name='catTwo',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('Finance', 'FINANCE'), ('Healthcare', 'HEALTHCARE'), ('Education', 'EDUCATION'), ('Marketing', 'MARKETING'), ('Design', 'DESIGN'), ('Engineering', 'ENGINEERING'), ('Customer Service', 'CUSTOMER_SERVICE'), ('Legal', 'LEGAL'), ('Sales', 'SALES'), ('Human Resources', 'HR'), ('Writing and Editing', 'WRITING_EDITING'), ('Data Science and Analytics', 'DATA_SCIENCE'), ('Project Management', 'PROJECT_MANAGEMENT'), ('Consulting', 'CONSULTING'), ('Operations', 'OPERATIONS'), ('Research and Development', 'RESEARCH_DEVELOPMENT'), ('Administrative Support', 'ADMIN_SUPPORT'), ('Construction', 'CONSTRUCTION'), ('Real Estate', 'REAL_ESTATE'), ('Entertainment and Media', 'ENTERTAINMENT_MEDIA'), ('Other', 'OTHER')], default='OTHER', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='projectoffer',
            name='image',
            field=models.ImageField(null=True, upload_to='project_images/'),
        ),
        migrations.CreateModel(
            name='CommetsOnFreelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
                ('stars', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fkFler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.freelancerprofile')),
            ],
        ),
    ]
